package platform

import "time"

type Repository interface {
	HomeModules() []HomeModule
	HomeCards() []HomeCard
	LoginWechatMini(req WechatMiniLoginRequest) (*WechatMiniLoginResult, error)
	SendPhoneVerificationCode(req SendPhoneVerificationCodeRequest) (*PhoneVerificationCodeTicket, error)
	LoginWithPhone(req PhoneLoginRequest) (*PhoneAuthResult, error)
	RegisterWithPhone(req PhoneRegisterRequest) (*PhoneAuthResult, error)
	CreateMerchantInvite(req CreateMerchantInviteRequest) (*MerchantOnboardingInvite, error)
	CreateMerchantInviteWithAudit(req CreateMerchantInviteRequest, audit RecordAuditLogRequest) (*MerchantOnboardingInvite, *AuditLog, error)
	AcceptMerchantInvite(req AcceptMerchantInviteRequest) (*MerchantProfile, error)
	LoginMerchant(req MerchantLoginRequest) (*MerchantProfile, error)
	CreateRiderInvite(req CreateRiderInviteRequest) (*MerchantOnboardingInvite, error)
	CreateRiderInviteWithAudit(req CreateRiderInviteRequest, audit RecordAuditLogRequest) (*MerchantOnboardingInvite, *AuditLog, error)
	AcceptRiderInvite(req AcceptRiderInviteRequest) (*RiderAccount, error)
	LoginRider(req RiderLoginRequest) (*RiderAccount, error)
	SaveMerchantQualification(req UploadMerchantQualificationRequest) (*MerchantProfile, error)
	AdminMerchantQualifications(req AdminMerchantQualificationListRequest) (*AdminMerchantQualificationList, error)
	AdminMerchantQualificationDetail(req AdminMerchantQualificationDetailRequest) (*AdminMerchantQualificationDetail, error)
	ReviewMerchantQualification(req ReviewMerchantQualificationRequest) (*MerchantProfile, *MerchantQualification, error)
	ReviewMerchantQualificationWithAudit(req ReviewMerchantQualificationRequest, audit RecordAuditLogRequest) (*MerchantProfile, *MerchantQualification, *AuditLog, *OutboxEvent, error)
	MerchantProfile(merchantID string) (*MerchantProfile, error)
	CreateNotification(req CreateNotificationRequest) (*PlatformNotification, error)
	Notifications(req NotificationListRequest) ([]PlatformNotification, error)
	MarkNotificationRead(req MarkNotificationReadRequest) (*PlatformNotification, error)
	RecordNotificationDelivery(req RecordNotificationDeliveryRequest) (*PlatformNotificationDelivery, error)
	NotificationDeliveries(req NotificationDeliveryListRequest) ([]PlatformNotificationDelivery, error)
	EmitNotificationFailureAlerts(req NotificationFailureAlertEmissionRequest, audit RecordAuditLogRequest) (*NotificationFailureAlertEmission, *OutboxEvent, *AuditLog, error)
	ScheduleNotificationDeliveryRetries(req NotificationDeliveryRetryScheduleRequest, audit RecordAuditLogRequest) (*NotificationDeliveryRetrySchedule, *OutboxEvent, *AuditLog, error)
	ScheduleNotificationQuietWindowRetries(req NotificationQuietWindowRetryScheduleRequest, audit RecordAuditLogRequest) (*NotificationDeliveryRetrySchedule, *OutboxEvent, *AuditLog, error)
	NotificationPreferences(req NotificationPreferenceListRequest) ([]NotificationPreference, error)
	SaveNotificationPreference(req SaveNotificationPreferenceRequest) (*NotificationPreference, error)
	SaveNotificationPreferenceWithAudit(req SaveNotificationPreferenceRequest, audit RecordAuditLogRequest) (*NotificationPreference, *AuditLog, error)
	SaveNotificationPreferenceBatchWithAudit(req SaveNotificationPreferenceBatchRequest, audit RecordAuditLogRequest) (*NotificationPreferenceBatchSaveResult, *AuditLog, error)
	MerchantStaff(merchantID string) ([]MerchantStaff, error)
	SaveMerchantStaff(req UpsertMerchantStaffRequest) (*MerchantStaff, error)
	MerchantSupplementalMaterials(merchantID string) ([]MerchantSupplementalMaterial, error)
	SaveMerchantSupplementalMaterial(req UploadMerchantSupplementalMaterialRequest) (*MerchantSupplementalMaterial, error)
	Shops() []Shop
	ShopDetail(shopID string) (*ShopDetail, error)
	ShopProducts(shopID string) ([]MerchantProduct, error)
	MerchantProducts(merchantID string, shopID string) ([]MerchantProduct, error)
	UpsertMerchantProduct(req UpsertMerchantProductRequest) (*MerchantProduct, error)
	SetMerchantProductStatus(req SetMerchantProductStatusRequest) (*MerchantProduct, error)
	ShopGroupbuyDeals(shopID string) ([]MerchantProduct, error)
	CreateGroupbuyOrder(req CreateGroupbuyOrderRequest) (*Order, error)
	UserGroupbuyVouchers(userID string) ([]GroupbuyVoucher, error)
	RedeemGroupbuyVoucher(req RedeemGroupbuyVoucherRequest) (*GroupbuyVoucher, *Order, error)
	SaveAddress(address UserAddress) (*UserAddress, error)
	UserAddresses(userID string) []UserAddress
	UpsertCartItem(req UpsertCartItemRequest) (*CartSummary, error)
	CartSummary(userID string, shopID string) (*CartSummary, error)
	CreateOrder(req CreateOrderRequest) (*Order, error)
	CheckoutCart(req CheckoutCartRequest) (*Order, *CartSummary, error)
	UserOrders(userID string) ([]Order, error)
	OrderByID(orderID string) (*Order, error)
	CreateReview(review Review) (*Review, error)
	UserReviews(req ReviewListRequest) ([]Review, error)
	CreateReviewImageUpload(req CreateReviewImageUploadRequest) (*ObjectUploadTicket, error)
	ConfirmReviewImageUpload(req ConfirmReviewImageUploadRequest) (*ReviewImageUploadTicket, error)
	CompensateOrderState(req CompensateOrderStateRequest) (*CompensateOrderStateResult, error)
	CompensateOrderStateWithAudit(req CompensateOrderStateRequest, audit RecordAuditLogRequest) (*CompensateOrderStateResult, *AuditLog, error)
	MerchantOrders(merchantID string) ([]Order, error)
	MerchantAcceptOrder(orderID string, merchantID string) (*Order, error)
	MerchantMarkOrderReady(orderID string, merchantID string) (*Order, error)
	CreditWallet(req CreditWalletRequest) (*WalletTransaction, *WalletAccount, error)
	WalletTransactions(userID string) ([]WalletTransaction, error)
	SetWalletPaymentPassword(req SetWalletPaymentPasswordRequest) (*WalletPaymentPasswordState, error)
	PayOrderWithBalance(req BalancePayRequest) (*WalletTransaction, *Order, *WalletAccount, error)
	RefundSettings() (*RefundSettings, error)
	SaveRefundSettings(req SaveRefundSettingsRequest) (*RefundSettings, error)
	SaveRefundSettingsWithAudit(req SaveRefundSettingsRequest, audit RecordAuditLogRequest) (*RefundSettings, *AuditLog, error)
	AdminRefundTransactions(req RefundTransactionListRequest) ([]RefundTransaction, error)
	RefundOrder(req RefundOrderRequest) (*RefundTransaction, *Order, *WalletAccount, error)
	RefundOrderWithAudit(req RefundOrderRequest, audit RecordAuditLogRequest) (*RefundTransaction, *Order, *WalletAccount, *AuditLog, error)
	AdminOperationsSnapshot(req AdminOperationsSnapshotRequest) (*AdminOperationsSnapshot, error)
	AdminOrderDetail(orderID string) (*AdminOrderDetail, error)
	CreateAfterSales(req CreateAfterSalesRequest) (*AfterSalesRequest, error)
	UserAfterSalesRequests(req AfterSalesListRequest) ([]AfterSalesRequest, error)
	MerchantAfterSalesRequests(merchantID string) ([]AfterSalesRequest, error)
	AdminAfterSalesRequests(req AfterSalesListRequest) ([]AfterSalesRequest, error)
	AdminAfterSalesDetail(requestID string) (*AdminAfterSalesDetail, error)
	AfterSalesEvents(requestID string, actorID string, actorRole string) ([]AfterSalesEvent, error)
	AddAfterSalesEvent(req AddAfterSalesEventRequest) (*AfterSalesEvent, *AfterSalesRequest, error)
	CreateAfterSalesEvidenceUpload(req CreateAfterSalesEvidenceUploadRequest) (*ObjectUploadTicket, error)
	ConfirmObjectStorageUpload(req ObjectStorageUploadCallbackRequest) (*AfterSalesEvidenceUploadTicket, error)
	RecordObjectStorageScanResult(req ObjectStorageScanResultRequest) (*AfterSalesEvidenceUploadTicket, error)
	ObjectStorageCleanupCandidates(req ObjectStorageCleanupCandidatesRequest) ([]ObjectStorageCleanupCandidate, error)
	CompleteObjectStorageCleanup(req ObjectStorageCleanupCompleteRequest) (*AfterSalesEvidenceUploadTicket, error)
	CompleteObjectStorageCleanupWithAudit(req ObjectStorageCleanupCompleteRequest, audit RecordAuditLogRequest) (*AfterSalesEvidenceUploadTicket, *AuditLog, error)
	RecordObjectStorageCleanupFailure(req ObjectStorageCleanupFailureRequest) (*AfterSalesEvidenceUploadTicket, error)
	RecordObjectStorageCleanupFailureWithAudit(req ObjectStorageCleanupFailureRequest, audit RecordAuditLogRequest) (*AfterSalesEvidenceUploadTicket, *AuditLog, error)
	ObjectStorageCleanupStats(req ObjectStorageCleanupCandidatesRequest) (*ObjectStorageCleanupStats, error)
	ConfirmAfterSalesEvidenceUpload(req ConfirmAfterSalesEvidenceUploadRequest) (*AfterSalesEvidence, *AfterSalesEvent, *AfterSalesRequest, error)
	AfterSalesEvidence(requestID string, actorID string, actorRole string) ([]AfterSalesEvidence, error)
	ReviewAfterSales(req ReviewAfterSalesRequest) (*AfterSalesRequest, *RefundTransaction, *Order, *WalletAccount, error)
	ReviewAfterSalesWithAudit(req ReviewAfterSalesRequest, audit RecordAuditLogRequest) (*AfterSalesRequest, *RefundTransaction, *Order, *WalletAccount, *AuditLog, error)
	CreateFeedback(ticket FeedbackTicket) (*FeedbackTicket, error)
	UserFeedbackTickets(userID string) ([]FeedbackTicket, error)
	CreateServiceTicket(req CreateServiceTicketRequest) (*ServiceTicketDetail, error)
	UserServiceTickets(userID string) ([]ServiceTicket, error)
	AdminServiceTicketDetail(ticketID string) (*ServiceTicketDetail, error)
	ServiceTicketDetail(userID string, ticketID string) (*ServiceTicketDetail, error)
	AddServiceTicketEvent(req AddServiceTicketEventRequest) (*ServiceTicketDetail, error)
	AdminServiceTickets(req ServiceTicketListRequest) ([]ServiceTicket, error)
	AssignServiceTicket(req AssignServiceTicketRequest) (*ServiceTicketDetail, error)
	ResolveServiceTicket(req ResolveServiceTicketRequest) (*ServiceTicketDetail, error)
	EscalateServiceTicket(req EscalateServiceTicketRequest) (*ServiceTicketDetail, error)
	ReviewServiceTicketQuality(req ServiceTicketQualityReviewRequest) (*ServiceTicketQualityReview, error)
	ServiceTicketQualityReviews(req ServiceTicketQualityReviewListRequest) ([]ServiceTicketQualityReview, error)
	ServiceTicketPerformance(req ServiceTicketPerformanceRequest) ([]ServiceTicketPerformanceSummary, error)
	CloseServiceTicket(req CloseServiceTicketRequest) (*ServiceTicketDetail, error)
	FollowUpServiceTicket(req FollowUpServiceTicketRequest) (*ServiceTicketDetail, error)
	UserProfileOverview(userID string) (*UserProfileOverview, error)
	CirclePosts(userID string) ([]CirclePost, error)
	CreateCirclePost(post CirclePost) (*CirclePost, error)
	SaveMealMatchProfile(profile MealMatchProfile) (*MealMatchProfile, error)
	UserMealMatchProfile(userID string) (*MealMatchProfile, error)
	MealMatchCandidates(userID string) (*MealMatchCandidateList, error)
	ReportMealMatchCandidate(req MealMatchReportRequest) (*MealMatchModerationRecord, error)
	BlockMealMatchCandidate(req MealMatchBlockRequest) (*MealMatchModerationRecord, error)
	AdminMealMatchModerationRecords(req MealMatchModerationListRequest) ([]MealMatchModerationRecord, error)
	ReviewMealMatchModeration(req MealMatchModerationReviewRequest) (*MealMatchModerationRecord, error)
	CreateRedPacket(packet RedPacket) (*RedPacketDetail, error)
	RedPacketDetail(packetID string, userID string) (*RedPacketDetail, error)
	ClaimRedPacket(packetID string, userID string) (*RedPacketClaimResult, error)
	RefundRedPacket(packetID string, userID string) (*RedPacketDetail, error)
	AutoRefundExpiredRedPackets(now time.Time) ([]RedPacketDetail, error)
	MessageThreads(userID string) ([]ChatThread, error)
	ChatThreadOverview(userID string, threadID string) (*ChatThreadOverview, error)
	ChatThreadMembers(userID string, threadID string) ([]ChatThreadMemberProfile, error)
	ChatThreadMembership(userID string, threadID string) (*ChatThreadMembership, error)
	JoinChatThread(req ChatThreadJoinRequest) (*ChatThreadMembership, error)
	LeaveChatThread(req ChatThreadLeaveRequest) (*ChatThreadMembership, error)
	ChatMessages(userID string, threadID string) ([]ChatMessage, error)
	ChatMessageSync(req ChatMessageSyncRequest) (*ChatMessageSyncResult, error)
	ChatThreadPreference(userID string, threadID string) (*ChatThreadPreference, error)
	UpdateChatThreadPreference(req UpdateChatThreadPreferenceRequest) (*ChatThreadPreference, error)
	MarkChatThreadRead(req MarkChatThreadReadRequest) (*ChatReadState, error)
	AuthorizeChatThreadAccess(req ChatThreadAccessRequest) (*ChatThreadAccessResult, error)
	SendChatMessage(message ChatMessage) (*ChatMessage, error)
	WalletOverview(userID string) (*WalletOverview, error)
	RequestWalletWithdraw(req WalletWithdrawRequest) (*WalletWithdrawRequest, *WalletAccount, error)
	UserCoupons(userID string) (*UserCouponsSummary, error)
	ClaimUserCoupon(userID string, code string) (*UserCoupon, error)
	UserPointsSummary(userID string) (*PointsSummary, error)
	CheckInPoints(userID string) (*PointsSummary, error)
	InviteSummary(userID string) (*InviteSummary, error)
	SearchCatalog(userID string, keyword string, category string) (*SearchCatalog, error)
	MedicineHome(userID string) (*MedicineHome, error)
	CreatePrescriptionImageUpload(req CreatePrescriptionImageUploadRequest) (*ObjectUploadTicket, error)
	ConfirmPrescriptionImageUpload(req ConfirmPrescriptionImageUploadRequest) (*PrescriptionImageUploadTicket, error)
	CreatePrescriptionReview(req CreatePrescriptionReviewRequest) (*PrescriptionReview, error)
	PrescriptionReview(userID string, reviewID string) (*PrescriptionReview, error)
	AdminPrescriptionReviews(req PrescriptionReviewListRequest) ([]PrescriptionReview, error)
	ReviewPrescription(req ReviewPrescriptionRequest) (*PrescriptionReview, error)
	CreateMedicineOrder(req MedicineOrderRequest) (*MedicineOrderDetail, error)
	MedicineOrderDetail(userID string, orderID string) (*MedicineOrderDetail, error)
	CreateErrandOrder(req ErrandOrderRequest) (*ErrandOrderDetail, error)
	ErrandOrderDetail(userID string, orderID string) (*ErrandOrderDetail, error)
	CreateWechatPrepay(req WechatPrepayRequest) (*WechatPrepayResponse, *PaymentTransaction, error)
	ConfirmWechatPayment(req WechatPaymentCallbackRequest) (*PaymentTransaction, *Order, error)
	DepositAccount(subjectType string, subjectID string) (*DepositAccount, error)
	PayDeposit(req PayDepositRequest) (*DepositAccount, error)
	ApproveRiderWechatExemption(req RiderWechatExemptionRequest) (*DepositAccount, *RiderAccount, error)
	RequestRiderDepositRefund(req RiderDepositRefundRequest) (*DepositAccount, *RiderAccount, error)
	SetRiderOnlineStatus(req SetRiderOnlineStatusRequest) (*RiderAccount, error)
	AutoAssignOrder(req AutoAssignOrderRequest) (*Order, *DispatchDecision, error)
	RejectRiderAssignment(req RejectRiderAssignmentRequest) (*Order, *DispatchDecision, error)
	TimeoutReassignOrder(req TimeoutReassignOrderRequest) (*Order, *DispatchDecision, error)
	StationRiders(stationManagerID string) ([]RiderAccount, error)
	StationOrders(stationManagerID string) ([]Order, error)
	ManualAssignOrder(req ManualAssignOrderRequest) (*Order, *DispatchDecision, error)
	StationTaskConfig(stationManagerID string) (*StationTaskConfig, error)
	SaveStationTaskConfig(req SaveStationTaskConfigRequest) (*StationTaskConfig, error)
	StationRiderPerformance(stationManagerID string) ([]RiderPerformance, error)
	DispatchEvents(orderID string, stationManagerID string) ([]DispatchEvent, error)
	OutboxEvents(req OutboxEventsRequest) ([]OutboxEvent, error)
	OutboxEventDetail(req OutboxEventDetailRequest) (*OutboxEventDetail, error)
	OutboxStats(req OutboxStatsRequest) (*OutboxStats, error)
	RecordAuditLog(req RecordAuditLogRequest) (*AuditLog, error)
	AuditLogs(req AuditLogsRequest) ([]AuditLog, error)
	AuditRetentionReport(req AuditRetentionReportRequest) (*AuditRetentionReport, error)
	EmitAuditRetentionAlerts(req AuditRetentionAlertEmissionRequest, audit RecordAuditLogRequest) (*AuditRetentionAlertEmission, *OutboxEvent, *AuditLog, error)
	RequestAuditArchive(req AuditArchiveRequest, audit RecordAuditLogRequest) (*AuditArchiveRequestResult, *OutboxEvent, *AuditLog, error)
	CompleteAuditArchive(req AuditArchiveCompletionRequest, audit RecordAuditLogRequest) (*AuditArchiveCompletion, *AuditLog, error)
	VerifyAuditArchive(req AuditArchiveVerifyRequest, audit RecordAuditLogRequest) (*AuditArchiveVerification, *AuditLog, error)
	AuditArchives(req AuditArchiveListRequest) ([]AuditArchiveCompletion, error)
	AuditArchiveVerifications(req AuditArchiveVerificationListRequest) ([]AuditArchiveVerification, error)
	MarkOutboxEventPublished(req MarkOutboxEventPublishedRequest) (*OutboxEvent, error)
	MarkOutboxEventPublishedWithAudit(req MarkOutboxEventPublishedRequest, audit RecordAuditLogRequest) (*OutboxEvent, *AuditLog, error)
	MarkOutboxEventFailed(req MarkOutboxEventFailedRequest) (*OutboxEvent, error)
	MarkOutboxEventFailedWithAudit(req MarkOutboxEventFailedRequest, audit RecordAuditLogRequest) (*OutboxEvent, *AuditLog, error)
	ClaimOutboxEvents(req ClaimOutboxEventsRequest) (*ClaimOutboxEventsResult, error)
	ClaimOutboxEventsWithAudit(req ClaimOutboxEventsRequest, audit RecordAuditLogRequest) (*ClaimOutboxEventsResult, *AuditLog, error)
	RenewOutboxEventLease(req RenewOutboxEventLeaseRequest) (*OutboxEvent, error)
	RenewOutboxEventLeaseWithAudit(req RenewOutboxEventLeaseRequest, audit RecordAuditLogRequest) (*OutboxEvent, *AuditLog, error)
	ReplayOutboxEvent(req ReplayOutboxEventRequest) (*OutboxEvent, error)
	ReplayOutboxEventWithAudit(req ReplayOutboxEventRequest, audit RecordAuditLogRequest) (*OutboxEvent, *AuditLog, error)
	ReplayOutboxEvents(req ReplayOutboxEventsRequest) (*ReplayOutboxEventsResult, error)
	ReplayOutboxEventsWithAudit(req ReplayOutboxEventsRequest, audit RecordAuditLogRequest) (*ReplayOutboxEventsResult, *AuditLog, error)
	GrabOrder(orderID string, riderID string) (*Order, error)
	RiderMarkOrderPickedUp(orderID string, riderID string) (*Order, error)
	RiderMarkOrderDelivered(orderID string, riderID string) (*Order, error)
	ConsumeFreeDispatchCancel(riderID string, at time.Time) (bool, string, error)
}

var _ Repository = (*Store)(nil)
