package platform

import "time"

type Repository interface {
	HomeModules() []HomeModule
	HomeCards() []HomeCard
	LoginWechatMini(req WechatMiniLoginRequest) (*WechatMiniLoginResult, error)
	CreateMerchantInvite(req CreateMerchantInviteRequest) (*MerchantOnboardingInvite, error)
	AcceptMerchantInvite(req AcceptMerchantInviteRequest) (*MerchantProfile, error)
	LoginMerchant(req MerchantLoginRequest) (*MerchantProfile, error)
	CreateRiderInvite(req CreateRiderInviteRequest) (*MerchantOnboardingInvite, error)
	AcceptRiderInvite(req AcceptRiderInviteRequest) (*RiderAccount, error)
	LoginRider(req RiderLoginRequest) (*RiderAccount, error)
	SaveMerchantQualification(req UploadMerchantQualificationRequest) (*MerchantProfile, error)
	MerchantProfile(merchantID string) (*MerchantProfile, error)
	MerchantStaff(merchantID string) ([]MerchantStaff, error)
	SaveMerchantStaff(req UpsertMerchantStaffRequest) (*MerchantStaff, error)
	MerchantSupplementalMaterials(merchantID string) ([]MerchantSupplementalMaterial, error)
	SaveMerchantSupplementalMaterial(req UploadMerchantSupplementalMaterialRequest) (*MerchantSupplementalMaterial, error)
	Shops() []Shop
	ShopProducts(shopID string) ([]MerchantProduct, error)
	MerchantProducts(merchantID string, shopID string) ([]MerchantProduct, error)
	UpsertMerchantProduct(req UpsertMerchantProductRequest) (*MerchantProduct, error)
	SetMerchantProductStatus(req SetMerchantProductStatusRequest) (*MerchantProduct, error)
	ShopGroupbuyDeals(shopID string) ([]MerchantProduct, error)
	CreateGroupbuyOrder(req CreateGroupbuyOrderRequest) (*Order, error)
	UserGroupbuyVouchers(userID string) ([]GroupbuyVoucher, error)
	RedeemGroupbuyVoucher(req RedeemGroupbuyVoucherRequest) (*GroupbuyVoucher, *Order, error)
	SaveAddress(address UserAddress) (*UserAddress, error)
	UserAddresses(userID string) []UserAddress
	UpsertCartItem(req UpsertCartItemRequest) (*CartSummary, error)
	CartSummary(userID string, shopID string) (*CartSummary, error)
	CreateOrder(req CreateOrderRequest) (*Order, error)
	CheckoutCart(req CheckoutCartRequest) (*Order, *CartSummary, error)
	UserOrders(userID string) ([]Order, error)
	OrderByID(orderID string) (*Order, error)
	CompensateOrderState(req CompensateOrderStateRequest) (*CompensateOrderStateResult, error)
	MerchantOrders(merchantID string) ([]Order, error)
	MerchantAcceptOrder(orderID string, merchantID string) (*Order, error)
	MerchantMarkOrderReady(orderID string, merchantID string) (*Order, error)
	CreditWallet(req CreditWalletRequest) (*WalletTransaction, *WalletAccount, error)
	SetWalletPaymentPassword(req SetWalletPaymentPasswordRequest) (*WalletPaymentPasswordState, error)
	PayOrderWithBalance(req BalancePayRequest) (*WalletTransaction, *Order, *WalletAccount, error)
	RefundSettings() (*RefundSettings, error)
	SaveRefundSettings(req SaveRefundSettingsRequest) (*RefundSettings, error)
	RefundOrder(req RefundOrderRequest) (*RefundTransaction, *Order, *WalletAccount, error)
	CreateAfterSales(req CreateAfterSalesRequest) (*AfterSalesRequest, error)
	UserAfterSalesRequests(userID string) ([]AfterSalesRequest, error)
	MerchantAfterSalesRequests(merchantID string) ([]AfterSalesRequest, error)
	AdminAfterSalesRequests() ([]AfterSalesRequest, error)
	AfterSalesEvents(requestID string, actorID string, actorRole string) ([]AfterSalesEvent, error)
	AddAfterSalesEvent(req AddAfterSalesEventRequest) (*AfterSalesEvent, *AfterSalesRequest, error)
	CreateAfterSalesEvidenceUpload(req CreateAfterSalesEvidenceUploadRequest) (*ObjectUploadTicket, error)
	ConfirmObjectStorageUpload(req ObjectStorageUploadCallbackRequest) (*AfterSalesEvidenceUploadTicket, error)
	RecordObjectStorageScanResult(req ObjectStorageScanResultRequest) (*AfterSalesEvidenceUploadTicket, error)
	ObjectStorageCleanupCandidates(req ObjectStorageCleanupCandidatesRequest) ([]ObjectStorageCleanupCandidate, error)
	CompleteObjectStorageCleanup(req ObjectStorageCleanupCompleteRequest) (*AfterSalesEvidenceUploadTicket, error)
	RecordObjectStorageCleanupFailure(req ObjectStorageCleanupFailureRequest) (*AfterSalesEvidenceUploadTicket, error)
	ObjectStorageCleanupStats(req ObjectStorageCleanupCandidatesRequest) (*ObjectStorageCleanupStats, error)
	ConfirmAfterSalesEvidenceUpload(req ConfirmAfterSalesEvidenceUploadRequest) (*AfterSalesEvidence, *AfterSalesEvent, *AfterSalesRequest, error)
	AfterSalesEvidence(requestID string, actorID string, actorRole string) ([]AfterSalesEvidence, error)
	ReviewAfterSales(req ReviewAfterSalesRequest) (*AfterSalesRequest, *RefundTransaction, *Order, *WalletAccount, error)
	CreateWechatPrepay(req WechatPrepayRequest) (*WechatPrepayResponse, *PaymentTransaction, error)
	ConfirmWechatPayment(req WechatPaymentCallbackRequest) (*PaymentTransaction, *Order, error)
	DepositAccount(subjectType string, subjectID string) (*DepositAccount, error)
	PayDeposit(req PayDepositRequest) (*DepositAccount, error)
	ApproveRiderWechatExemption(req RiderWechatExemptionRequest) (*DepositAccount, *RiderAccount, error)
	RequestRiderDepositRefund(req RiderDepositRefundRequest) (*DepositAccount, *RiderAccount, error)
	SetRiderOnlineStatus(req SetRiderOnlineStatusRequest) (*RiderAccount, error)
	AutoAssignOrder(req AutoAssignOrderRequest) (*Order, *DispatchDecision, error)
	RejectRiderAssignment(req RejectRiderAssignmentRequest) (*Order, *DispatchDecision, error)
	TimeoutReassignOrder(req TimeoutReassignOrderRequest) (*Order, *DispatchDecision, error)
	StationRiders(stationManagerID string) ([]RiderAccount, error)
	StationOrders(stationManagerID string) ([]Order, error)
	ManualAssignOrder(req ManualAssignOrderRequest) (*Order, *DispatchDecision, error)
	StationTaskConfig(stationManagerID string) (*StationTaskConfig, error)
	SaveStationTaskConfig(req SaveStationTaskConfigRequest) (*StationTaskConfig, error)
	StationRiderPerformance(stationManagerID string) ([]RiderPerformance, error)
	DispatchEvents(orderID string, stationManagerID string) ([]DispatchEvent, error)
	OutboxEvents(req OutboxEventsRequest) ([]OutboxEvent, error)
	OutboxStats(req OutboxStatsRequest) (*OutboxStats, error)
	MarkOutboxEventPublished(req MarkOutboxEventPublishedRequest) (*OutboxEvent, error)
	MarkOutboxEventFailed(req MarkOutboxEventFailedRequest) (*OutboxEvent, error)
	ClaimOutboxEvents(req ClaimOutboxEventsRequest) (*ClaimOutboxEventsResult, error)
	RenewOutboxEventLease(req RenewOutboxEventLeaseRequest) (*OutboxEvent, error)
	ReplayOutboxEvent(req ReplayOutboxEventRequest) (*OutboxEvent, error)
	ReplayOutboxEvents(req ReplayOutboxEventsRequest) (*ReplayOutboxEventsResult, error)
	GrabOrder(orderID string, riderID string) (*Order, error)
	RiderMarkOrderPickedUp(orderID string, riderID string) (*Order, error)
	RiderMarkOrderDelivered(orderID string, riderID string) (*Order, error)
	ConsumeFreeDispatchCancel(riderID string, at time.Time) (bool, string, error)
}

var _ Repository = (*Store)(nil)
